CIRCUITPY_CREATOR_ID =  0x0000239A
CIRCUITPY_CREATION_ID = 0x00c30003

IDF_TARGET = esp32c3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESP_USB_SERIAL_JTAG = 1

# Not enough pins.
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_RGBMATRIX = 0

# Enable debug output
CIRCUITPY_DEBUG = 1
CIRCUITPY_VERBOSE_BUILD = 1
